# Dependencies
rogue:            true

# Permalinks
permalink:        pretty

# Setup
title:            Calum Shepherd
tagline:          Product Lead — UK PropTech & Agentic AI
url:              https://calumshepherd.com
baseurl:          /
author:
  name:           Calum Shepherd
  url:            https://x.com/calumshepherd
  email:

# Custom vars
version:          1.0.0
github:
  repo:           https://github.com/poole/poole

# Sitemaps
gems:
  - jekyll-sitemap
